ip:
  first:
    host: 192.168.50.223
    port: 1883
    priority: 1
  second:
    host: 10.255.252.152
    port: 1883
    priority: 2
  third:
    host: localhost
    port: 1883
    priority: 3
  
vehicle: vehicle/3

mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    port: 1883
    keepalive: 60
  private_path: device/001
#serializer: json:dumps
#deserializer: json:loads
bridge:
    # Publish Odometry from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: /state_estimation
    topic_to: Odometry
    # Subscribe Odometry from MQTT to ROS
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: vehicle/+/Odometry
    topic_to: /pong
    # Publish Covered Subspace Indices from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int32MultiArray
    topic_from: /sensor_coverage_planner/Covered_Subspace_Indices
    topic_to: Covered_subspaces
    # Subscribe Covered Subspace Indices from MQTT to ROS  
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Int32MultiArray
    topic_from: vehicle/+/Covered_subspaces
    topic_to: /covered_subspaces
    # Publish Exploring Subspace Indices from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int32MultiArray
    topic_from: /sensor_coverage_planner/Exploring_Subspace_Indices
    topic_to: Exploring_subspaces
    # Subscribe Exploring Subspace Indices from MQTT to ROS  
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Int32MultiArray
    topic_from: vehicle/+/Exploring_subspaces
    topic_to: /exploring_subspaces_2
    # Publish Robot Priority from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Int32
    topic_from: /Priority
    topic_to: Priority
    # Subscribe Robot Priority from MQTT to ROS  
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Int32
    topic_from: vehicle/+/Priority
    topic_to: /ugv2priority
    # Publish Availability from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /Availability
    topic_to: Availability
    # Subscribe Availability from MQTT to ROS  
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: vehicle/+/Availability
    topic_to: /ugv2priority
    # Publish Availability from ROS to MQTT
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: geometry_msgs.msg:PointStamped
    topic_from: /tare_way_point
    topic_to: tare_waypoint
    # Subscribe Availability from MQTT to ROS  
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: geometry_msgs.msg:PointStamped
    topic_from: vehicle/+/tare_waypoint
    topic_to: /ugv2priority
